CONF_GROUPS = "groups"
CONF_LIGHT_ENTITIES = "light_entities"
CONF_LIGHTS_COLOR_CONTROL = "color_control"
# CONF_LIGHTS_CT = "lights_ct"
# CONF_LIGHTS_RGB = "lights_rgb"
# CONF_LIGHTS_XY = "lights_xy"
# CONF_LIGHTS_BRIGHT = "lights_brightness"
CONF_DISABLE_BRIGHTNESS_ADJUST = "disable_brightness_adjust"
CONF_CT_SOURCE = "ct_source"
CONF_BRIGHT_SOURCE = "bri_source"
CONF_MIN_BRIGHT, DEFAULT_MIN_BRIGHT = "min_brightness", 1
CONF_MAX_BRIGHT, DEFAULT_MAX_BRIGHT = "max_brightness", 100
CONF_MIN_CT, DEFAULT_MIN_BRIGHT = "min_ct", 0.0  # TODO: Replace this guess with actual value
CONF_MAX_CT, DEFAULT_MAX_BRIGHT = "max_ct", 1.0  # TODO: Replace this guess with actual value
# CONF_SLEEP_ENTITY = "sleep_entity"
# CONF_SLEEP_STATE = "sleep_state"
# CONF_SLEEP_CT, DEFAULT_SLEEP_CT = "sleep_colortemp", 1000
# CONF_SLEEP_BRIGHT, DEFAULT_SLEEP_BRIGHT = "sleep_brightness", 1
# CONF_DISABLE_ENTITY = "disable_entity"
# CONF_DISABLE_STATE = "disable_state"
CONF_INITIAL_TRANSITION, DEFAULT_INITIAL_TRANSITION = "initial_transition", 1
CONF_TRANSITION, DEFAULT_TRANSITION = "transition", 1
CONF_ONLY_ONCE = "only_once"
